/**
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *        http://www.apache.org/licenses/LICENSE-2.0
 *        
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.politaktiv.meinungsbild.infrastructure.model;

import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Rating service. Represents a row in the &quot;meinungsbild_Rating&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.politaktiv.meinungsbild.infrastructure.model.impl.RatingModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.politaktiv.meinungsbild.infrastructure.model.impl.RatingImpl}.
 * </p>
 *
 * @author politaktiv
 * @see Rating
 * @see org.politaktiv.meinungsbild.infrastructure.model.impl.RatingImpl
 * @see org.politaktiv.meinungsbild.infrastructure.model.impl.RatingModelImpl
 * @generated
 */
public interface RatingModel extends BaseModel<Rating> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a rating model instance should use the {@link Rating} interface instead.
	 */

	/**
	 * Returns the primary key of this rating.
	 *
	 * @return the primary key of this rating
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this rating.
	 *
	 * @param primaryKey the primary key of this rating
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the rating ID of this rating.
	 *
	 * @return the rating ID of this rating
	 */
	public long getRatingId();

	/**
	 * Sets the rating ID of this rating.
	 *
	 * @param ratingId the rating ID of this rating
	 */
	public void setRatingId(long ratingId);

	/**
	 * Returns the user ID of this rating.
	 *
	 * @return the user ID of this rating
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this rating.
	 *
	 * @param userId the user ID of this rating
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this rating.
	 *
	 * @return the user uuid of this rating
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this rating.
	 *
	 * @param userUuid the user uuid of this rating
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the subtopic ID of this rating.
	 *
	 * @return the subtopic ID of this rating
	 */
	public long getSubtopicId();

	/**
	 * Sets the subtopic ID of this rating.
	 *
	 * @param subtopicId the subtopic ID of this rating
	 */
	public void setSubtopicId(long subtopicId);

	/**
	 * Returns the score of this rating.
	 *
	 * @return the score of this rating
	 */
	public int getScore();

	/**
	 * Sets the score of this rating.
	 *
	 * @param score the score of this rating
	 */
	public void setScore(int score);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Rating rating);

	public int hashCode();

	public CacheModel<Rating> toCacheModel();

	public Rating toEscapedModel();

	public String toString();

	public String toXmlString();
}