/**
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *        http://www.apache.org/licenses/LICENSE-2.0
 *        
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.politaktiv.meinungsbild.infrastructure.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Subtopic service. Represents a row in the &quot;meinungsbild_Subtopic&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.politaktiv.meinungsbild.infrastructure.model.impl.SubtopicModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.politaktiv.meinungsbild.infrastructure.model.impl.SubtopicImpl}.
 * </p>
 *
 * @author politaktiv
 * @see Subtopic
 * @see org.politaktiv.meinungsbild.infrastructure.model.impl.SubtopicImpl
 * @see org.politaktiv.meinungsbild.infrastructure.model.impl.SubtopicModelImpl
 * @generated
 */
public interface SubtopicModel extends BaseModel<Subtopic> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a subtopic model instance should use the {@link Subtopic} interface instead.
	 */

	/**
	 * Returns the primary key of this subtopic.
	 *
	 * @return the primary key of this subtopic
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this subtopic.
	 *
	 * @param primaryKey the primary key of this subtopic
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the subtopic ID of this subtopic.
	 *
	 * @return the subtopic ID of this subtopic
	 */
	public long getSubtopicId();

	/**
	 * Sets the subtopic ID of this subtopic.
	 *
	 * @param subtopicId the subtopic ID of this subtopic
	 */
	public void setSubtopicId(long subtopicId);

	/**
	 * Returns the name of this subtopic.
	 *
	 * @return the name of this subtopic
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this subtopic.
	 *
	 * @param name the name of this subtopic
	 */
	public void setName(String name);

	/**
	 * Returns the url of this subtopic.
	 *
	 * @return the url of this subtopic
	 */
	@AutoEscape
	public String getUrl();

	/**
	 * Sets the url of this subtopic.
	 *
	 * @param url the url of this subtopic
	 */
	public void setUrl(String url);

	/**
	 * Returns the parent topic of this subtopic.
	 *
	 * @return the parent topic of this subtopic
	 */
	public long getParentTopic();

	/**
	 * Sets the parent topic of this subtopic.
	 *
	 * @param parentTopic the parent topic of this subtopic
	 */
	public void setParentTopic(long parentTopic);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Subtopic subtopic);

	public int hashCode();

	public CacheModel<Subtopic> toCacheModel();

	public Subtopic toEscapedModel();

	public String toString();

	public String toXmlString();
}