/**
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *        http://www.apache.org/licenses/LICENSE-2.0
 *        
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.politaktiv.meinungsbild.infrastructure.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Topic service. Represents a row in the &quot;meinungsbild_Topic&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.politaktiv.meinungsbild.infrastructure.model.impl.TopicModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.politaktiv.meinungsbild.infrastructure.model.impl.TopicImpl}.
 * </p>
 *
 * @author politaktiv
 * @see Topic
 * @see org.politaktiv.meinungsbild.infrastructure.model.impl.TopicImpl
 * @see org.politaktiv.meinungsbild.infrastructure.model.impl.TopicModelImpl
 * @generated
 */
public interface TopicModel extends BaseModel<Topic> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a topic model instance should use the {@link Topic} interface instead.
	 */

	/**
	 * Returns the primary key of this topic.
	 *
	 * @return the primary key of this topic
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this topic.
	 *
	 * @param primaryKey the primary key of this topic
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the topic ID of this topic.
	 *
	 * @return the topic ID of this topic
	 */
	public long getTopicId();

	/**
	 * Sets the topic ID of this topic.
	 *
	 * @param topicId the topic ID of this topic
	 */
	public void setTopicId(long topicId);

	/**
	 * Returns the name of this topic.
	 *
	 * @return the name of this topic
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this topic.
	 *
	 * @param name the name of this topic
	 */
	public void setName(String name);

	/**
	 * Returns the community ID of this topic.
	 *
	 * @return the community ID of this topic
	 */
	public long getCommunityId();

	/**
	 * Sets the community ID of this topic.
	 *
	 * @param communityId the community ID of this topic
	 */
	public void setCommunityId(long communityId);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Topic topic);

	public int hashCode();

	public CacheModel<Topic> toCacheModel();

	public Topic toEscapedModel();

	public String toString();

	public String toXmlString();
}