/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.politaktiv.meinungsbild.infrastructure.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Topic service. Represents a row in the &quot;meinungsbild_Topic&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.politaktiv.meinungsbild.infrastructure.model.impl.TopicModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.politaktiv.meinungsbild.infrastructure.model.impl.TopicImpl}.
 * </p>
 *
 * @author politaktiv
 * @see Topic
 * @see org.politaktiv.meinungsbild.infrastructure.model.impl.TopicImpl
 * @see org.politaktiv.meinungsbild.infrastructure.model.impl.TopicModelImpl
 * @generated
 */
public interface TopicModel extends BaseModel<Topic> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a topic model instance should use the {@link Topic} interface instead.
	 */

	/**
	 * Returns the primary key of this topic.
	 *
	 * @return the primary key of this topic
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this topic.
	 *
	 * @param primaryKey the primary key of this topic
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the topic ID of this topic.
	 *
	 * @return the topic ID of this topic
	 */
	public long getTopicId();

	/**
	 * Sets the topic ID of this topic.
	 *
	 * @param topicId the topic ID of this topic
	 */
	public void setTopicId(long topicId);

	/**
	 * Returns the name of this topic.
	 *
	 * @return the name of this topic
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this topic.
	 *
	 * @param name the name of this topic
	 */
	public void setName(String name);

	/**
	 * Returns the community ID of this topic.
	 *
	 * @return the community ID of this topic
	 */
	public long getCommunityId();

	/**
	 * Sets the community ID of this topic.
	 *
	 * @param communityId the community ID of this topic
	 */
	public void setCommunityId(long communityId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Topic topic);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Topic> toCacheModel();

	@Override
	public Topic toEscapedModel();

	@Override
	public Topic toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}