/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.politaktiv.meinungsbild.infrastructure.service.base;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.service.BaseServiceImpl;
import com.liferay.portal.service.persistence.UserPersistence;

import org.politaktiv.meinungsbild.infrastructure.model.Topic;
import org.politaktiv.meinungsbild.infrastructure.service.TopicService;
import org.politaktiv.meinungsbild.infrastructure.service.persistence.RatingPersistence;
import org.politaktiv.meinungsbild.infrastructure.service.persistence.SubtopicPersistence;
import org.politaktiv.meinungsbild.infrastructure.service.persistence.TopicPersistence;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the topic remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link org.politaktiv.meinungsbild.infrastructure.service.impl.TopicServiceImpl}.
 * </p>
 *
 * @author politaktiv
 * @see org.politaktiv.meinungsbild.infrastructure.service.impl.TopicServiceImpl
 * @see org.politaktiv.meinungsbild.infrastructure.service.TopicServiceUtil
 * @generated
 */
public abstract class TopicServiceBaseImpl extends BaseServiceImpl
	implements TopicService, IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link org.politaktiv.meinungsbild.infrastructure.service.TopicServiceUtil} to access the topic remote service.
	 */

	/**
	 * Returns the rating local service.
	 *
	 * @return the rating local service
	 */
	public org.politaktiv.meinungsbild.infrastructure.service.RatingLocalService getRatingLocalService() {
		return ratingLocalService;
	}

	/**
	 * Sets the rating local service.
	 *
	 * @param ratingLocalService the rating local service
	 */
	public void setRatingLocalService(
		org.politaktiv.meinungsbild.infrastructure.service.RatingLocalService ratingLocalService) {
		this.ratingLocalService = ratingLocalService;
	}

	/**
	 * Returns the rating remote service.
	 *
	 * @return the rating remote service
	 */
	public org.politaktiv.meinungsbild.infrastructure.service.RatingService getRatingService() {
		return ratingService;
	}

	/**
	 * Sets the rating remote service.
	 *
	 * @param ratingService the rating remote service
	 */
	public void setRatingService(
		org.politaktiv.meinungsbild.infrastructure.service.RatingService ratingService) {
		this.ratingService = ratingService;
	}

	/**
	 * Returns the rating persistence.
	 *
	 * @return the rating persistence
	 */
	public RatingPersistence getRatingPersistence() {
		return ratingPersistence;
	}

	/**
	 * Sets the rating persistence.
	 *
	 * @param ratingPersistence the rating persistence
	 */
	public void setRatingPersistence(RatingPersistence ratingPersistence) {
		this.ratingPersistence = ratingPersistence;
	}

	/**
	 * Returns the subtopic local service.
	 *
	 * @return the subtopic local service
	 */
	public org.politaktiv.meinungsbild.infrastructure.service.SubtopicLocalService getSubtopicLocalService() {
		return subtopicLocalService;
	}

	/**
	 * Sets the subtopic local service.
	 *
	 * @param subtopicLocalService the subtopic local service
	 */
	public void setSubtopicLocalService(
		org.politaktiv.meinungsbild.infrastructure.service.SubtopicLocalService subtopicLocalService) {
		this.subtopicLocalService = subtopicLocalService;
	}

	/**
	 * Returns the subtopic remote service.
	 *
	 * @return the subtopic remote service
	 */
	public org.politaktiv.meinungsbild.infrastructure.service.SubtopicService getSubtopicService() {
		return subtopicService;
	}

	/**
	 * Sets the subtopic remote service.
	 *
	 * @param subtopicService the subtopic remote service
	 */
	public void setSubtopicService(
		org.politaktiv.meinungsbild.infrastructure.service.SubtopicService subtopicService) {
		this.subtopicService = subtopicService;
	}

	/**
	 * Returns the subtopic persistence.
	 *
	 * @return the subtopic persistence
	 */
	public SubtopicPersistence getSubtopicPersistence() {
		return subtopicPersistence;
	}

	/**
	 * Sets the subtopic persistence.
	 *
	 * @param subtopicPersistence the subtopic persistence
	 */
	public void setSubtopicPersistence(SubtopicPersistence subtopicPersistence) {
		this.subtopicPersistence = subtopicPersistence;
	}

	/**
	 * Returns the topic local service.
	 *
	 * @return the topic local service
	 */
	public org.politaktiv.meinungsbild.infrastructure.service.TopicLocalService getTopicLocalService() {
		return topicLocalService;
	}

	/**
	 * Sets the topic local service.
	 *
	 * @param topicLocalService the topic local service
	 */
	public void setTopicLocalService(
		org.politaktiv.meinungsbild.infrastructure.service.TopicLocalService topicLocalService) {
		this.topicLocalService = topicLocalService;
	}

	/**
	 * Returns the topic remote service.
	 *
	 * @return the topic remote service
	 */
	public org.politaktiv.meinungsbild.infrastructure.service.TopicService getTopicService() {
		return topicService;
	}

	/**
	 * Sets the topic remote service.
	 *
	 * @param topicService the topic remote service
	 */
	public void setTopicService(
		org.politaktiv.meinungsbild.infrastructure.service.TopicService topicService) {
		this.topicService = topicService;
	}

	/**
	 * Returns the topic persistence.
	 *
	 * @return the topic persistence
	 */
	public TopicPersistence getTopicPersistence() {
		return topicPersistence;
	}

	/**
	 * Sets the topic persistence.
	 *
	 * @param topicPersistence the topic persistence
	 */
	public void setTopicPersistence(TopicPersistence topicPersistence) {
		this.topicPersistence = topicPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		Class<?> clazz = getClass();

		_classLoader = clazz.getClassLoader();
	}

	public void destroy() {
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	@Override
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	@Override
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	@Override
	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		Thread currentThread = Thread.currentThread();

		ClassLoader contextClassLoader = currentThread.getContextClassLoader();

		if (contextClassLoader != _classLoader) {
			currentThread.setContextClassLoader(_classLoader);
		}

		try {
			return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
		}
		finally {
			if (contextClassLoader != _classLoader) {
				currentThread.setContextClassLoader(contextClassLoader);
			}
		}
	}

	protected Class<?> getModelClass() {
		return Topic.class;
	}

	protected String getModelClassName() {
		return Topic.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = topicPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = org.politaktiv.meinungsbild.infrastructure.service.RatingLocalService.class)
	protected org.politaktiv.meinungsbild.infrastructure.service.RatingLocalService ratingLocalService;
	@BeanReference(type = org.politaktiv.meinungsbild.infrastructure.service.RatingService.class)
	protected org.politaktiv.meinungsbild.infrastructure.service.RatingService ratingService;
	@BeanReference(type = RatingPersistence.class)
	protected RatingPersistence ratingPersistence;
	@BeanReference(type = org.politaktiv.meinungsbild.infrastructure.service.SubtopicLocalService.class)
	protected org.politaktiv.meinungsbild.infrastructure.service.SubtopicLocalService subtopicLocalService;
	@BeanReference(type = org.politaktiv.meinungsbild.infrastructure.service.SubtopicService.class)
	protected org.politaktiv.meinungsbild.infrastructure.service.SubtopicService subtopicService;
	@BeanReference(type = SubtopicPersistence.class)
	protected SubtopicPersistence subtopicPersistence;
	@BeanReference(type = org.politaktiv.meinungsbild.infrastructure.service.TopicLocalService.class)
	protected org.politaktiv.meinungsbild.infrastructure.service.TopicLocalService topicLocalService;
	@BeanReference(type = org.politaktiv.meinungsbild.infrastructure.service.TopicService.class)
	protected org.politaktiv.meinungsbild.infrastructure.service.TopicService topicService;
	@BeanReference(type = TopicPersistence.class)
	protected TopicPersistence topicPersistence;
	@BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
	protected com.liferay.counter.service.CounterLocalService counterLocalService;
	@BeanReference(type = com.liferay.portal.service.ResourceLocalService.class)
	protected com.liferay.portal.service.ResourceLocalService resourceLocalService;
	@BeanReference(type = com.liferay.portal.service.UserLocalService.class)
	protected com.liferay.portal.service.UserLocalService userLocalService;
	@BeanReference(type = com.liferay.portal.service.UserService.class)
	protected com.liferay.portal.service.UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private ClassLoader _classLoader;
	private TopicServiceClpInvoker _clpInvoker = new TopicServiceClpInvoker();
}