/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.politaktiv.meinungsbild.infrastructure.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import org.politaktiv.meinungsbild.infrastructure.model.Rating;
import org.politaktiv.meinungsbild.infrastructure.model.RatingModel;
import org.politaktiv.meinungsbild.infrastructure.model.RatingSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Rating service. Represents a row in the &quot;meinungsbild_Rating&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link org.politaktiv.meinungsbild.infrastructure.model.RatingModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RatingImpl}.
 * </p>
 *
 * @author politaktiv
 * @see RatingImpl
 * @see org.politaktiv.meinungsbild.infrastructure.model.Rating
 * @see org.politaktiv.meinungsbild.infrastructure.model.RatingModel
 * @generated
 */
@JSON(strict = true)
public class RatingModelImpl extends BaseModelImpl<Rating>
	implements RatingModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a rating model instance should use the {@link org.politaktiv.meinungsbild.infrastructure.model.Rating} interface instead.
	 */
	public static final String TABLE_NAME = "meinungsbild_Rating";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ratingId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "subtopicId", Types.BIGINT },
			{ "score", Types.INTEGER }
		};
	public static final String TABLE_SQL_CREATE = "create table meinungsbild_Rating (ratingId LONG not null primary key,userId LONG,subtopicId LONG,score INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table meinungsbild_Rating";
	public static final String ORDER_BY_JPQL = " ORDER BY rating.ratingId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY meinungsbild_Rating.ratingId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.org.politaktiv.meinungsbild.infrastructure.model.Rating"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.org.politaktiv.meinungsbild.infrastructure.model.Rating"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.org.politaktiv.meinungsbild.infrastructure.model.Rating"),
			true);
	public static long SUBTOPICID_COLUMN_BITMASK = 1L;
	public static long USERID_COLUMN_BITMASK = 2L;
	public static long RATINGID_COLUMN_BITMASK = 4L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Rating toModel(RatingSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Rating model = new RatingImpl();

		model.setRatingId(soapModel.getRatingId());
		model.setUserId(soapModel.getUserId());
		model.setSubtopicId(soapModel.getSubtopicId());
		model.setScore(soapModel.getScore());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Rating> toModels(RatingSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Rating> models = new ArrayList<Rating>(soapModels.length);

		for (RatingSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.org.politaktiv.meinungsbild.infrastructure.model.Rating"));

	public RatingModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _ratingId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setRatingId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _ratingId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Rating.class;
	}

	@Override
	public String getModelClassName() {
		return Rating.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("ratingId", getRatingId());
		attributes.put("userId", getUserId());
		attributes.put("subtopicId", getSubtopicId());
		attributes.put("score", getScore());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long ratingId = (Long)attributes.get("ratingId");

		if (ratingId != null) {
			setRatingId(ratingId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		Long subtopicId = (Long)attributes.get("subtopicId");

		if (subtopicId != null) {
			setSubtopicId(subtopicId);
		}

		Integer score = (Integer)attributes.get("score");

		if (score != null) {
			setScore(score);
		}
	}

	@JSON
	@Override
	public long getRatingId() {
		return _ratingId;
	}

	@Override
	public void setRatingId(long ratingId) {
		_ratingId = ratingId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_columnBitmask |= USERID_COLUMN_BITMASK;

		if (!_setOriginalUserId) {
			_setOriginalUserId = true;

			_originalUserId = _userId;
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	public long getOriginalUserId() {
		return _originalUserId;
	}

	@JSON
	@Override
	public long getSubtopicId() {
		return _subtopicId;
	}

	@Override
	public void setSubtopicId(long subtopicId) {
		_columnBitmask |= SUBTOPICID_COLUMN_BITMASK;

		if (!_setOriginalSubtopicId) {
			_setOriginalSubtopicId = true;

			_originalSubtopicId = _subtopicId;
		}

		_subtopicId = subtopicId;
	}

	public long getOriginalSubtopicId() {
		return _originalSubtopicId;
	}

	@JSON
	@Override
	public int getScore() {
		return _score;
	}

	@Override
	public void setScore(int score) {
		_score = score;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			Rating.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Rating toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Rating)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		RatingImpl ratingImpl = new RatingImpl();

		ratingImpl.setRatingId(getRatingId());
		ratingImpl.setUserId(getUserId());
		ratingImpl.setSubtopicId(getSubtopicId());
		ratingImpl.setScore(getScore());

		ratingImpl.resetOriginalValues();

		return ratingImpl;
	}

	@Override
	public int compareTo(Rating rating) {
		long primaryKey = rating.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Rating)) {
			return false;
		}

		Rating rating = (Rating)obj;

		long primaryKey = rating.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		RatingModelImpl ratingModelImpl = this;

		ratingModelImpl._originalUserId = ratingModelImpl._userId;

		ratingModelImpl._setOriginalUserId = false;

		ratingModelImpl._originalSubtopicId = ratingModelImpl._subtopicId;

		ratingModelImpl._setOriginalSubtopicId = false;

		ratingModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Rating> toCacheModel() {
		RatingCacheModel ratingCacheModel = new RatingCacheModel();

		ratingCacheModel.ratingId = getRatingId();

		ratingCacheModel.userId = getUserId();

		ratingCacheModel.subtopicId = getSubtopicId();

		ratingCacheModel.score = getScore();

		return ratingCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(9);

		sb.append("{ratingId=");
		sb.append(getRatingId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", subtopicId=");
		sb.append(getSubtopicId());
		sb.append(", score=");
		sb.append(getScore());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(16);

		sb.append("<model><model-name>");
		sb.append("org.politaktiv.meinungsbild.infrastructure.model.Rating");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>ratingId</column-name><column-value><![CDATA[");
		sb.append(getRatingId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>subtopicId</column-name><column-value><![CDATA[");
		sb.append(getSubtopicId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>score</column-name><column-value><![CDATA[");
		sb.append(getScore());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Rating.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] { Rating.class };
	private long _ratingId;
	private long _userId;
	private String _userUuid;
	private long _originalUserId;
	private boolean _setOriginalUserId;
	private long _subtopicId;
	private long _originalSubtopicId;
	private boolean _setOriginalSubtopicId;
	private int _score;
	private long _columnBitmask;
	private Rating _escapedModel;
}