/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.politaktiv.meinungsbild.infrastructure.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import org.politaktiv.meinungsbild.infrastructure.model.Subtopic;
import org.politaktiv.meinungsbild.infrastructure.service.SubtopicLocalServiceUtil;

/**
 * The extended model base implementation for the Subtopic service. Represents a row in the &quot;meinungsbild_Subtopic&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SubtopicImpl}.
 * </p>
 *
 * @author politaktiv
 * @see SubtopicImpl
 * @see org.politaktiv.meinungsbild.infrastructure.model.Subtopic
 * @generated
 */
public abstract class SubtopicBaseImpl extends SubtopicModelImpl
	implements Subtopic {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a subtopic model instance should use the {@link Subtopic} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			SubtopicLocalServiceUtil.addSubtopic(this);
		}
		else {
			SubtopicLocalServiceUtil.updateSubtopic(this);
		}
	}
}